### PR TITLE
Removed Passport.js

### PR DESCRIPTION
**Pull request by williamj1788**
Here is a proposal to remove passport.js.

Overall, I feel that Passport makes our authentication process more complex than it needs to be.
What should be a straight forward process is made convoluted by having to understand another library and read unnecessary documentation to do something that could be easily written by ourselves.

I have decided to instead implement our own authentication code for reason I will list now:

### CODE REVIEW

**Comment by rohitkrishna094** [comment]
I do like this approach. But I have one question. Would it be better to make getUser work in a way so it doesn't have to depend on verifyToken to come before it.

If we want to make a route secured and also get user obj in the process, we can just add getUser Middleware without having to worry about verifyToken. What do you think?

**Comment by williamj1788** [comment]
While that would be nice, I don't think we should do that. We should design our middleware to do only one thing and one thing only, because they became easier to understand and test (if we ever decide to do that). If we allow getUser to be able to verify the token and get the user all in the same we have:
> 1. duplicate code with the verifyToken middleware.
> 2. just using the getUser in a route doesn't convey enough information to the consumer. Like "getUser" sounds like you are only getting the user, but instead its "verifying the token and using the id to get the user".
> 3. In our routes, we can easily tell if a route is protected by the visual sign of "verifyToken", but if we allow other middleware to do that also, it could lead to some confusion on whether the route is private or not.

I could config the getUser middleware to allow the user_id to be passed in through req.body or req.param in instead of just relying on the token, but this lead to more problems down the line. And a route should be either protected or not (either you have to be logged in to use a route or not).

**Comment by rohitkrishna094** [comment]
> 1) However whenever we use getUser in a route, we will have to duplicate the verifyToken before that. Not to mention since this dependency exists and also has to come first would mean that this is prone to errors. 
> 2) Yes, just using getUser might not convey that. We would need to change the name to something like authenticateUser or getAuthenticatedUser
> 3) Again, it comes to naming convention of the method

The main point that I believe is that we will never use getUser on its own. It always has a dependency on verifyToken. Hence whenever we use it, we will be duplicating code of having verifyToken and getUser as middleware. This is a perfect thing to refactor since getUser will never be called without verifyToken being called first. Not to mention, anyone new will now have to keep in mind that verifyToken should come before getUser which will make things complex down the line.

Also when it comes to testing we will be writing unit tests. Since we will write tests for verifyToken, we will also write tests for authenticateUser. authenticateUser would then have a dependency on verifyToken and since in unit tests we assume that every other dependecy or method works while testing the current method. So we just have to mock and stub verifyToken and test authenticateUser's functionality. 

Right now this might seem simple, but tomorrow if we add more filters or middleware then it will only get harder for us to track which filter should come first and so on.

The main point is here that getUser on its own is never used without verifyToken's functionality. Hence whatever you say, getUser has a dependency on verifyToken. I don't see any benefit of getUser as a standalone functionality. We will use verifyToken as a standalone in some routes. we will use authenticateUser in some routes, but we will never use getUser on its own without verifyToken. 

That's why I believe we should just include verify functionality in it.

**Comment by 404kacper** [comment]
Passport will also make it easier for us to implement facebook/twitter/instagram... etc. login

**Comment by williamj1788** [comment]
I understand some of your concerns about having to manage middleware dependencies, but I still think that we can solve that problem without having to resort to multi-function middlewares.

Let us use some fictional router as an example.

Will my current proposal it would look something like this:
```js

const { verifyToken, getUser } = require("./shared/authenticate");

router.post('/', verifyToken,, (req, res) => {
  // this endpoint needs the UserID or just needs to verify the token
})

router.post('/:paramData', verifyToken, (req, res) => {
  // this endpoint needs the UserID or just needs to verify the token
})

router.get('/', (req, res) => {
  // this endpoint doesn't need to verify the token 
})

router.get('/:paramData', (req, res) => {
  // this endpoint doesn't need to verify the token 
})

router.patch('/', verifyToken, getUser, (req, res) => {
  // this endpoint needs to verify the token but also needs the user object
})

router.patch('/someFakeUrl', verifyToken, getUser, (req, res) => {
 // this endpoint needs to verify the token but also needs the user object
})

router.put('/', verifyToken, (req, res) => {
  // this endpoint needs the UserID or just needs to verify the token
})

router.put('/someFakeUrl', verifyToken, (req, res) => {
  // this endpoint needs the UserID or just needs to verify the token
})
```

As you can see some routes needs to just verify the token and others also need the user object. if you want the user object then you have to use both verifyToken and getUser in order. I going to assume that you are proposing a middleware that does both verify the token and gets the user (let just call it "authenticateUser").

So the router will look like this instead:

```js

const { verifyToken, getUser } = require("./shared/authenticate");

router.post('/', verifyToken,, (req, res) => {

})

router.post('/:paramData', verifyToken, (req, res) => {

})

router.get('/', (req, res) => {

})

router.get('/:paramData', (req, res) => {

})

router.patch('/', authenticateUser, (req, res) => {
  // this endpoint uses "authenticateUser" which does both verifyToken and getUser
})

router.patch('/someFakeUrl', authenticateUser, (req, res) => {
 // this endpoint uses "authenticateUser" which does both verifyToken and getUser
})

router.put('/', verifyToken, (req, res) => {

})

router.put('/someFakeUrl', verifyToken, (req, res) => {

})
```
This approach does get rid of the middleware dependencies, so we don't have to worry about getUser having to depend on verifyToken, but I think we can do this other way instead

```js

const { verifyToken, getUser } = require("./shared/authenticate");

router.post('/', verifyToken,, (req, res) => {

})

router.post('/:paramData', verifyToken, (req, res) => {

})

router.get('/', (req, res) => {

})

router.get('/:paramData', (req, res) => {

})


router.patch('/', authenticateUser, (req, res) => {
  // this endpoint uses "authenticateUser" which does both verifyToken and getUser
})

router.patch('/someFakeUrl', authenticateUser, (req, res) => {
 // this endpoint uses "authenticateUser" which does both verifyToken and getUser
})

router.put('/', verifyToken, (req, res) => {

})

router.put('/someFakeUrl', verifyToken, (req, res) => {

})
```

**Comment by williamj1788** [comment]
Was going to write a detail response explaining how we could manage the middleware dependency, but stop because about halfway I thought to my self, "Man, I could have written some really productive code today, but instead I decide to write a long Github comment". Alright, we can keep passport but still going to propose some changes, because I don't think it was set-up right.

**Comment by rohitkrishna094** [comment]
@williamj1788 I do like the approach of removing passportjs. Again this is still up for discussion on my end. Sorry if you were offended for any reason. And @404kacper makes a good point about oauth as well. I have never worked with oauth in node, so I am not sure if writing it on our own is easier or not. 

But again, this is still up for discussion. I do like the idea of removing dependencies. If you are still up for it, we could merge your PR(with getUser and verifyToken as is and use both of them whenever we need to secure a route). But before doing that, I do want to ask if you've worked with oauth before without passportjs, since we do plan on adding support for some of the major oauth providers in future. 

Again sorry if you were offended for any reason. I was just asking a question. Also coding is not the only thing that's important in a real project. Most of the time goes into discussing and planning stuff anyway. At least that's what I believe. Have a nice day.

**Pull request closed without merging**
